---
title: "Marketing Data"

---
In this exercise, I analyze a marketing data set from Kaggle. The tasks are the following.

## Section 01: Exploratory Data Analysis:
Are there any null values or outliers? How will you wrangle/handle them?

Are there any variables that warrant transformations?

Are there any useful variables that you can engineer with the given data?

Do you notice any patterns or anomalies in the data? Can you plot them?


## Section 02: Statistical Analysis
Please run statistical tests in the form of regressions to answer these questions & propose data-driven action recommendations to your CMO. Make sure to interpret your results with non-statistical jargon so your CMO can understand your findings.

What factors are significantly related to the number of store purchases?

Does US fare significantly better than the Rest of the World in terms of total purchases?

Your supervisor insists that people who buy gold are more conservative. Therefore, people who spent an above average amount on gold in the last 2 years would have more in store purchases. Justify or refute this statement using an appropriate statistical test

Fish has Omega 3 fatty acids which are good for the brain. Accordingly, do "Married PhD candidates" have a significant relation with amount spent on fish? What other factors are significantly related to amount spent on fish? (Hint: use your knowledge of interaction variables/effects)

Is there a significant relationship between geographical regional and success of a campaign?

## Section 03: Data Visualization
Please plot and visualize the answers to the below questions.

Which marketing campaign is most successful?

What does the average customer look like for this company?

Which products are performing best?

Which channels are underperforming?


## Section 04: CMO Recommendations
Bring together everything from Sections 01 to 03 and provide data-driven recommendations/suggestions to your CMO.